require("prototypes.autoplace-controls")
require("prototypes.noise-layers")

require("prototypes.resources.glittery-rock")

require("prototypes.items.coke")
require("prototypes.items.glittery-rock")
require("prototypes.items.glitter")
require("prototypes.items.trixie")
require("prototypes.items.glittery-plastic-bar")

require("prototypes.fluids.cog")
require("prototypes.fluids.methanol")
require("prototypes.fluids.ethanol")
require("prototypes.fluids.glittery-goop")
require("prototypes.fluids.glittery-juice")
require("prototypes.fluids.glittery-gas")

require("prototypes.recipes.glitter")
require("prototypes.recipes.coke")
require("prototypes.recipes.cog")
require("prototypes.recipes.methanol")
require("prototypes.recipes.ethanol")
require("prototypes.recipes.trixie")
require("prototypes.recipes.glittery-goop")
require("prototypes.recipes.glittery-juice")
require("prototypes.recipes.glittery-gas")
require("prototypes.recipes.glittery-plastic-bar")

require("prototypes.technology.cog")
require("prototypes.technology.methanol")
require("prototypes.technology.ethanol")
require("prototypes.technology.glitter")
